### ISSUE TITLE
NullReferenceException on startup

### ISSUE THREAD

**Issue by anihilnine** [AgoraIO-Community/agora-unity-partychat-demo#1]
I am having trouble getting started ... I have checked out the repository and cannot get it to run. I am using 2018.4.18f1 which is the same as what was checked in.

![image](https://user-images.githubusercontent.com/7132727/112400704-a16d5b80-8d54-11eb-915b-35241c30a380.png)
1. I get a null error because photonView it null
2. As you can see I have set my photon app Id
3. It looks suspicious to me that the prefab is not filled in - no spawn point, content, etc
4. And there is nothing in the hierarchy that looks like it should go in those places

Thank you

**Comment by joelthomas362** [comment]
Hey @anihilnine, I totally can see how this mix-up could occur, that's my mistake. Can you please check out the [new front page](https://github.com/AgoraIO-Community/agora-unity-partychat-demo) of this repo, and let me know if there is anything else I can add to help you get started? 

Thanks!
